chairc/Integrated-Design-Diffusion-Model

- tools/generate.py
- utils/utils.py
New feature, we update save images. You can save one image in the tensor of images.
> Add: Add show and save image in images.

- utils/initializer.py
- utils/utils.py
[Add function comments.](https://github.com/chairc/Industrial-Defect-Diffusion-Model/commit/6365ddd6378d80178e9ec72a4862efdad4081473)
[Update: Update model.parameters() and add SGD optimizer.](https://github.com/chairc/Industrial-Defect-Diffusion-Model/commit/7a209a7d6dc1a5ed20c5edebbbbe37adfe760771)
> Add function comments; Update model.parameters() and add SGD optimizer.

- README.md
- README_zh.md
- tools/train.py
- utils/checkpoint.py
[Add pretrain ckeckpoint method.](https://github.com/chairc/Industrial-Defect-Diffusion-Model/commit/792df1e87afc3185880b2d8dbc6c63c19c14a127)
> Add: Add pretrain ckeckpoint method.

- README.md
- README_zh.md
- tools/train.py
- utils/initializer.py
Update: Modify automatic mixed precision training name; reconstruct automatic mixed precision training structure.
> Update: Modify automatic mixed precision training name; reconstruct automatic mixed precision training structure.

- test/test_module.py
- tools/generate.py
- tools/train.py
- utils/checkpoint.py
- utils/initializer.py
- utils/utils.py
[Add: Add new save checkpoint parameters.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/f82faeb82a8880f3740332080dc63fbe611ca754)
[Add: Add generate_initializer function, and check the parameters.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/c60b9b868d9f53396783fe977ef1f6e0ee4bec56)
[Add: Add resize function, use temporary ANTIALIAS to resample the low images](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/e924275f59c4de49f5909862fba72ca0134e7ceb)
[Add: Add the test ckpt parameters.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/574531aeedd3635d16c2104758e866c10e16fa87)
[Update: Refactor generate.py.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/5b818323400d10e974e9b678d933a3eeadfda7 …
> Major update about generating images

- model/samples/ddim.py
- tools/generate.py
- tools/train.py
[Update: Modify some parameters and formats.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/6e8233431d7a3e23107d5a3bd749d84b7cbe9e9f)
[Update: Generate images in new folder.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/60ecfb81a9f654b5d562157834ea8596d3a35eed)
> Modify some parameters and formats; Generate images in new folder.

- README.md
- README_zh.md
- tools/generate.py
[Update: Modify comment.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/7cc4d00ebd8942fba7c4eb862f77e953822c365e)
[Update: Modify README, add issue link and correct some text.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/929cfb9f6bb7e0301cb09afbbd843bf00879ab44)
> Modify comment; Modify README, add issue link and correct some text.

- tools/train.py
- utils/initializer.py
[Update: Modify the GPU settings. CPU training is not supported after version 1.1.2](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/8b8ee1186203c16ea8edc1c2583d5ebb624392ec)
[Update: Modify automatic mixed precision setting, optimize GradScaler.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/03e3f3050961e8611bbe84e3599c420727d0e90d)
> Modify the GPU settings. CPU training is not supported after version 1.1.2; Modify automatic mixed precision setting, optimize GradScaler.

- model/samples/base.py
- model/samples/ddim.py
- model/samples/ddpm.py
- utils/initializer.py
- utils/utils.py
[Update: Modify information prompt problems.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/4b8f41ff7c2475aa91af83fb7bd66124a2bb9308)
[Update: Modify beta_end.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/fc47f69f348df116e4da9cd1e3c0876677919ebc)
[Add: Add sqrt_linear and sqrt schedules.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/c6204d52e1e03e8730b48e00028e156d2fec3c6f)
> Modify information prompt problems; Modify beta_end; Add sqrt_linear and sqrt schedules.

- README.md
- README_zh.md
- model/modules/block.py
- model/modules/module.py
- model/networks/sr/srv1.py
- sr/dataset.py
- sr/demo.py
- sr/interface.py
- sr/train.py
- utils/initializer.py
- utils/utils.py
[Add: Add super resolution model (The implement of RDN), low images to high.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/75708bb141efeaca80a77d36af71e5652c302b4b)
> Add: Add super resolution model (The implement of RDN), low images to high.

- tools/generate.py
- utils/utils.py
Allows selection to the format of the generated images, offering options between 'jpg' and 'png'.
> Generation image format

- tools/generate.py
- utils/checkpoint.py
[Add: Add option to load EMA model.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/261b9269fa141976ac010ad908fb02769095f279)
> Add: Add option to load EMA model.

- README.md
- README_zh.md
[Update: Modify Chinese introduction errors and add --image_format parameter introduction.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/40129e8b098f375886f675327c0f981c750848da)
> Update: Modify Chinese introduction errors and add --image_format parameter introduction.

- model/samples/plms.py
- utils/initializer.py
[Add PLMS sampler.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/b1a381aa07a2da503dea24bb53f90f3fe6719933)
[Add PLMS sample initializer.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/1fdc6279327da2895d4c044d85db2744818bb31e)
> Add PLMS sampler; Add PLMS sample initializer.

- config/version.py
[Add: Add version.py.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/5b1d4a656d592c6d3367af2e079bf864511aff02)
> Add version.py.

- README.md
- README_zh.md
- tools/train.py
- utils/checkpoint.py
[Add: Add --save_model_interval_epochs parameter. Save model interval and save it every X epochs.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/737e9a9cb73cf1a33797094d7b590c4bb45146bc)
[Add: Add --save_model_interval_epochs parameter in README.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/138c14dcf2136cb07d03e790fe8080189aab64cf)
> Add --save_model_interval_epochs parameter. Save model interval and save it every X epochs.

- config/choices.py
- sr/dataset.py
- sr/interface.py
- tools/generate.py
- utils/utils.py
[Update: Modify the mean, std and random resized crop settings in torchvision.transforms.Compose.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/42f004d5bf2b962c1f3c55ac31e99fc77fe86bc3)
[Update: Modify the choices in parser and adjust the order of parts.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/db203b322c1878aed09689492ddc3fdf08901470)
> Modify the mean, std and random resized crop settings in torchvision.transforms.Compose; Modify the choices in parser and adjust the order of parts.

- tools/FID_calculator.py
> FID calculator used for evaluating generated images.

- config/__init__.py
- model/modules/__init__.py
- model/networks/__init__.py
- model/samples/__init__.py
- sr/dataset.py
- sr/train.py
- test/test_module.py
- tools/train.py
- utils/__init__.py
- utils/dataset.py
- utils/utils.py
[Update: Separate get dataset methods into data files.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/57686bbccf0e4e0ecc01cc44a2251dc558b9b101)
[Add: Add initialization operation of utils.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/52d6c124b124cd6a9bbdf55049e45859ac22b4b4)
[Add: Add initialization operation of modules.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/6e46b5465619ca7fb9b7f9ce46d04c6da59b9c7e)
[Add: Add initialization operation of networks.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/3639b6ed7645ab5da135816e2cca219ce371a043)
[Add: Add initialization operation of diffusion samples.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/f1127979f9ad1101f7aa9e43d18c605bd3967701 …
> Separate get dataset methods into data files; Add initialization operation.

- README.md
- README_zh.md
[Update: Modify repository structure, parameter explanation and citation.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/ee094381223b36a5027f4ea223189df23e90d16e)
> Update: Modify repository structure, parameter explanation and citation.

- README.md
- README_zh.md
[Add: Add Evaluation in README.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/c9b48a27303739e92c12f926e3390ae505bd2563)
> Add: Add Evaluation in README.

- README.md
- README_zh.md
[Update: Modify type description error in README.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/689dd6675dd98ddf6d093f318e04610426ead64d)
> Update: Modify type description error in README.

- webui/web.py
[Update: Refactor web.py, and add the generate page.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/95354b4f7ac0ae57e4df53512b3c65d2e0eaf615)
> Update: Refactor web.py, and add the generate page.

- config/choices.py
- model/modules/attention.py
- model/networks/base.py
- model/networks/cspdarkunet.py
- model/networks/unet.py
- model/networks/unetv2.py
- model/samples/base.py
- model/samples/ddim.py
- model/samples/ddpm.py
- model/samples/plms.py
- test/test_module.py
- tools/generate.py
- tools/train.py
- utils/check.py
- utils/dataset.py
- utils/initializer.py
- utils/utils.py
[Update: Modify custom images length and width input.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/d467066b19247a9853176671afc83e3e6e716afd)
[Update: Sample initialization judgment enhancement.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/00971509c604202ec7a50eaec36b61acd639d7e3)
[Update: generate_initializer logger enhancement.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/81e39ab0bee75bdf5fcb298f8bb159a1da7c6d34)
[Update: "Image.ANTIALIAS" method has been deprecated and replaced with "Image.LANCZOS".](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/ae83e2b1f573257186f429a5e5be8d1180e034b4)
> Modify custom images length and width input; Other code enhancement changes

- config/__init__.py
- config/choices.py
- config/setting.py
- sr/dataset.py
- sr/interface.py
- sr/train.py
- tools/train.py
- utils/dataset.py
- webui/web.py
[Add: Add custom parameter settings, this file stores static constant settings.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/b36719ad8f3e8db966a854bcfac4ff680ea04f14)
[Update: Modify the method import path and eliminate the magic value.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/315dcb8088c7cf860213bc57733c7d0fb2f9cb75)
>  Add custom parameter settings; Modify the method import path and eliminate the magic value

- tools/generate.py
- utils/check.py
Modify the format (generate.py) and delete useless import in check.py
> Update: Modify the format and delete useless import

- README.md
- README_zh.md
[Update: Update the README.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/212bac68d56b4e36b9e12c90acf6dd6357f60aae)
> Update: Update the README.

- tools/train.py
- utils/utils.py
- webui/web.py
[Update: Modify check_and_create_dir function.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/7e6f955c6e7f7e7238ac441b665a0bbe475490ce)
[Update: Modify comment.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/2d9c6a47253892a6022295bd3b8f7e44dc75f667)
> Modify check_and_create_dir function; Modify comment.

- tools/generate.py
[Fix: Fix the problem of lack parameters when input --image_size.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/27d44360ebc776d713a5c877e8f139e2ee467bf8)
> Fix: Fix the problem of lack parameters when input --image_size.

- config/version.py
[Add: Add v1.1.6 tag.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/c3742acde494f9e88b03ac8f18b1ed7805fd9638)
> Add: Add v1.1.6 tag.

- datasets/README.md
- datasets/README_zh.md
[Update: Modify the README in datasets.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/78d2fa0ce369900b3ea7db6412357c20b8ebff67)
[Add: Add the Chinese README in datasets.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/a2a870f642109a21be9d6625d31209d94322492d)
> Modify the README in datasets; Add the Chinese README in datasets.

- test/test_module.py
- utils/check.py
[Add: Add the NaN check method.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/c4acb67648df8f17e541d4ed8dcc21b91a5db6d9)
> Add: Add the NaN check method.

- requirements.txt
- tools/FID_calculator.py
[Add date, author and site description.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/ccd7d0b0bbc276bdf10963957287df4117490bc3)
[Update require packages.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/959c268f84c7e8a54c9b916fd6ab6754203b620f)
> Add date, author and site description; Update require packages.

- sr/train.py
- tools/train.py
- utils/utils.py
- webui/web.py
[Fix: Remove two imshow() duplicate functions.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/828a8422a83fdf664339b8ebeb3b4a2f377e7307)
[Update: Remove magic transforms and eval function.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/95f4bf1a0fe698c2a68ebab845dbc634d3ac2de7)
[Update: Replace images.shape[0] to batch_size.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/595f9126fb9b2128dcffb7db989e457687bbb5a0)
> Remove two imshow() duplicate functions; Remove magic transforms and eval function; Replace images.shape[0] to batch_size.

- README.md
- README_zh.md
- deploy/deploy_server.py
- deploy/deploy_socket.py
- requirements.txt
[Add: Added deploy support (server and socket).](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/2e8cd13531ed0d33c9dcd43fc95175968c0e0f7a)
> Add: Added deploy support (server and socket).

- requirements.txt
- sr/train.py
- tools/train.py
- utils/checkpoint.py
- utils/metrics.py
[Update: Parameters decomposed into methods.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/33025112bf672af6c31c7791d406451098d46a3a)
[Add: Added PSNR and SSIM calculators to verify super resolution image quality and optimize super resolution train.py.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/399ddeadf820278eb4e348a357ccad8cb87ef1c6)
[Update: Update requirements.txt.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/e880be93d7188932c29b040036731edaf56b0a1a)
> Parameters decomposed into methods; Added PSNR and SSIM calculators; Update requirements.txt.

- .gitignore
- config/model_list.py
- config/setting.py
- deploy/__init__.py
- test/test_module.py
- utils/check.py
- utils/utils.py
[Update: Update deploy init.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/14881f9b8a077a392dafbd684c440398de59767a)
[Update: Update gitignore.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/40697afc54a65a997eef54d2b60889df0db8895b)
[Add: Add official model list.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/6f230d642b6c0ae340eed224f0e41e0f62872d1a)
[Add: Add download model function.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/9ad1bd5ffd53f6642eedca74164b1be12b22549b)
> Update model list

- tools/generate.py
[Add: Add use_gpu params.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/b432297a198cbd13b9801993b230ffa237165c2b)
> Add: Add use_gpu params.

- sr/interface.py
[Fix the bug where the pixels of the image exceed 255 or less than 0.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/58f990699791fe193784937030599ae86a9a6e28)
> Fix: Fix the bug where the pixels of the image exceed 255 or less than 0.

- sr/train.py
- tools/generate.py
- tools/train.py
[Update: Update the short name trigger parameter.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/5198a3c8c3ecf03e5f4d11f92be97770bead8f37)
> Update: Update the short name trigger parameter.

- README.md
- README_zh.md
- sr/train.py
- tools/generate.py
- tools/train.py
[docs: Fix neu-120-weight.pt pre-training model download link.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/3cc715d08e08715a2e57992c013147c2f09a4ccd)
[docs: Update README.md, add gitcode star badge.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/8f4b00e47e29d9e6007c054a49516e83dca747fd)
[docs: Update README_zh.md, add gitcode star badge.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/4b0425813b41145a938d4c038bce79f0d46d0360)
> docs: Update README.

- README.md
- README_zh.md
[docs: Update username.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/46b9114cc69c5b30173ca3ddbc56165edb48e1bf)
> docs: Update username.

- config/version.py
- setup.py
[chore: Add version 1.1.8 tag.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/8ad5e4b61271a55a9e6d4638c091c36f59994ef9)
[feat: Add Pypi setup tool.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/0167ed6375307aec5d94121ddec9f6efb068b115)
> Add version 1.1.8 tag and Pypi setup tool.

- README.md
- README_zh.md
- docs/zh-Hans/03_生成.md
[docs: Delete id.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/78c8f8b104ed68d7973a103978331f3b98b04229)
[docs: Update new README.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/5bb210b8ec9d6418d795c451dda6bf2ef547de59)
> Update new README.

- iddm/model/samples/base.py
- iddm/model/samples/ddim.py
- iddm/model/samples/ddpm.py
- iddm/model/samples/plms.py
- iddm/model/trainers/base.py
- iddm/model/trainers/dm.py
- iddm/model/trainers/sr.py
- iddm/utils/checkpoint.py
[refactor: Refactor model's samples.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/3958a85f1dbcb4ccc04082e7c7a8950aa58f4f96)
[refactor: Refactor model's trainer checkpoint.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/edd788283d25dcf6a97d93161e4c665aeb7fc2b5)
[refactor: Refactor train_in_epochs function.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/b55f99d4d07f8b925c8b45256ccc649185a117da)
[feat: Added a common function for obtaining sampler images.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/a93aa9f9cdfd5d7fb8fd50845ad94a88104e3014)
> Refactor model samples and trainer

- iddm/config/choices.py
- iddm/model/samples/dpmpp.py
- iddm/utils/initializer.py
> feat: Add dpmpp sample.

- Dockerfile
[feat(docker): Add docker file running test.](https://github.com/chairc/Integrated-Design-Diffusion-Model/commit/c68469117fb22b5be8ace89cb3b5b95d9c87d7ed)
> feat(docker): Add docker file running test.
